version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASS: admin
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_URL=db
    depends_on:
      - db